### PR TITLE
Deprecations for 0.9 release

### PR DESCRIPTION
**Pull request by cisaacstern**
This PR implements planned deprecations in advance of the `0.9` release:

- XarrayZarrRecipe manual stage functions (we'd initially planned to deprecate these in `0.8`, but forgot to then).
- FilePattern `is_opendap` kwarg which is superseded by `file_type="opendap"`

### CODE REVIEW

**Review by rabernat — APPROVED** [review]
Thanks for doing this important maintenance.

**Comment by cisaacstern** [comment]
I think the last thing here is to mention these depreciations in the release notes. I'll do that first thing tomorrow, then merge and release 0.9.

**Comment by cisaacstern** [comment]
On further thought, I think I'll update release notes in a separate PR, so that I can include any other highlights for this release.

**Pull request merged**
