### PR TITLE
python 3.10 support

### PR DESCRIPTION
**Pull request by rabernat**

### CODE REVIEW

**Comment by rabernat** [comment]
All the python 3.10 tests are failing due to inability to import beam.

```
pangeo_forge_recipes/executors/__init__.py:20: in <module>
    from .beam import BeamPipelineExecutor
pangeo_forge_recipes/executors/beam.py:5: in <module>
    import apache_beam as beam
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/__init__.py:93: in <module>
    from apache_beam import io
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/io/__init__.py:21: in <module>
    from apache_beam.io.avroio import *
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/io/avroio.py:53: in <module>
    from apache_beam.io import filebasedsink
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/io/filebasedsink.py:29: in <module>
    from apache_beam.io import iobase
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/io/iobase.py:54: in <module>
    from apache_beam.transforms import Impulse
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/transforms/__init__.py:22: in <module>
    from apache_beam.transforms import combiners
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/transforms/combiners.py:39: in <module>
    from apache_beam.transforms import core
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/transforms/core.py:2795: in <module>
    @typehints.with_input_types(typing.Tuple[K, V])
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/typehints/decorators.py:772: in with_input_types
    native_type_compatibility.convert_to_beam_types(positional_hints))
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/typehints/native_type_compatibility.py:311: in convert_to_beam_types
    return [convert_to_beam_type(v) for v in args]
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/typehints/native_type_compatibility.py:311: in <listcomp>
    return [convert_to_beam_type(v) for v in args]
/usr/share/miniconda3/envs/pangeo-forge-recipes/lib/python3.10/site-packages/apache_beam/typehints/native_type_compatibility.py:[28](https://github.com/pangeo-forge/pangeo-forge-recipes/actions/runs/3894606664/jobs/6648936187#step:9:29)3: in convert_to_beam_type
    raise ValueError(
E   ValueError: expecting type typing.Tuple[~K, ~V] to have arity 0, had arity 2 instead
```

**Comment by rabernat** [comment]
Tagging @alxmrs, our resident beam expert, in case he sees a quick resolution for this.

**Comment by alxmrs** [comment]
Happy New Year, Ryan! 

I just encountered this error last December. Check out this issue:

https://github.com/apache/beam/issues/24685

As I understand it, Python 3.10 support is currently in development for Beam. However, this error was the first time that it's broken for us in XArray-Beam.

**Comment by alxmrs** [comment]
PS: I bet the Beam devs would be appreciative of a fix to this issue in their type checker — it seems like it could be a sweet one-liner 😉

**Comment by rabernat** [comment]
Nice try Alex, but I cannot be nerd-swiped so easily. 😎

If only there were someone on our team who was already familiar with the problem and had a good idea of how to fix it...oh well. 😔

**Comment by cisaacstern** [comment]
Seems like the beam refactor sidestepped this issue (or it was solved upstream but the linked issue never closed?). Either way, we currently run the full test suite against python 3.10 and 3.11 and it all works, so closing. 🎉

**Pull request closed without merging**
