### PR TITLE
Add binder links to tutorials

### PR DESCRIPTION
**Pull request by cisaacstern**
In anticipation of our OSM tutorial, it seems worth lowering the barrier for new users to actually run our tutorials. Binder links work great for this purpose. A few notes about the implementation:

- The custom Binder env follows the example of https://github.com/pangeo-gallery/default-binder
- The env itself seemed to logically fit within `pangeo-forge-bakery-images`, so I added it there https://github.com/pangeo-forge/pangeo-forge-bakery-images/pull/26

I used https://jupyterhub.github.io/nbgitpuller/link to generate the link, with the following params

<table>
<tr><th>Binderhub URL</th><td>https://mybinder.org</td></tr>
<tr><th>Git Environment Repository URL</th><td> https://github.com/pangeo-forge/pangeo-forge-bakery-images (branch: <code>binder</code>)</td></tr>
<tr><th>Git Content Repository URL</th><td>https://github.com/pangeo-forge/pangeo-forge-recipes (branch: <code>master</code>)</td></tr>
<tr><th>File to open</th><td>/docs/tutorials/xarray_zarr/netcdf_zarr_sequential.ipynb (or similar...) </td></tr>
<tr><th>Application to open</th><td>Classic Jupyter Notebook</td></tr>
</table>

I then generated the badge URL with https://mybinder.readthedocs.io/en/latest/howto/badges.html

cc @rwegener2

### CODE REVIEW

**Comment by rabernat** [comment]
I am trying the binders now. Everything seems to work.

Two suggestions:
- Have the binders open in jupyterLab, not classic notebook.
- Add a general binder link to the main tutorials/index.md page which points to the tutorials folder. That way people can launch all the tutorials in one go.

**Comment by rwegener2** [comment]
Such an important step, @cisaacstern!

I noticed there wasn't a binder link on the introduction tutorial. I know I just proposed a change to that whole section, but eventually I think it would be great to have a binder link there as well.

**Comment by cisaacstern** [comment]
Noting that our new plan is just to put a single JupyterLab link at the index.

**Comment by rwegener2** [comment]
@cisaacstern Can I confirm that the plan is to now do both Binder links and put the Jupyterlab link at the index? I think both are helpful if it isn't too big a lift.

**Pull request closed without merging**
