### PR TITLE
Bugfix to allow opening of zarr files (Resolves #454)

### LINKED ISSUE #454: Bug when trying to open zarr files
@cisaacstern @rabernat 

Charles and I found a bug in trying to write the recipe in pangeo-forge/staged-recipes#239. Running the recipe throws an error, which he realized would also be triggered by running this:

```
import xarray as xr
import fsspec

file = xr.open_dataset(fsspec.open("https://g-402b74.00888.8540.data.globus.org/eddy/low_res.zarr"), engine="zarr")
```

which appears to be the current behavior, where the expected behavior would be:

```
file = xr.open_dataset("https://g-402b74.00888.8540.data.globus.org/eddy/low_res.zarr", engine="zarr")
```

The error I get is `ValueError: Starting with Zarr 2.11.0, stores must be subclasses of BaseStore, if your store exposes the MutableMapping interface wrap it in Zarr.storage.KVStore. Got <OpenFile 'https://g-402b74.00888.8540.data.globus.org/eddy/low_res.zarr'>`

### PR DESCRIPTION
**Pull request by cmdupuis3**
See issue #454 for details.

This bugfix basically implements a new zarr filetype akin to the Opendap type.

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks a lot for this Chris!

Since we decide to skip unit tests for this feature, could you please give a summary of the validation you have done to ensure that this actually works?

**Comment by rabernat** [comment]
Let's try to get this in today and then cut a new release. Together with #383 we have some new features to get out.

**Comment by cisaacstern** [comment]
Agreed easiest to combine these into a single release. 👍

**Comment by cmdupuis3** [comment]
> Since we decide to skip unit tests for this feature, could you please give a summary of the validation you have done to ensure that this actually works?

For validation, I tested my recipe from [here](url), with and without the changes. The recipe appears to work correctly with these changes.

**Comment by cisaacstern** [comment]
Thanks @cmdupuis3!

I'll work up release notes and cut a release now.

**Pull request merged**
