### PR TITLE
Define contribution process

### PR DESCRIPTION
**Pull request by rabernat**
As noted by @ciaranevans in https://github.com/pangeo-forge/roadmap/issues/9, our docs on contributing a recipe are now obsolete. This PR gets started on updating that page. Before we can really write that, we need to answer a few questions.

- What is the expected structure of a user-contributed recipe? What files does it have to contain? What conventions should they follow?
- Pangeo Forge can be used in a standalone way, separate from the whole cloud infrastructure; you can write and execute your recipe alone and never "contribute" it to the database of recipes. How do we discuss / distinguish this situation in the documentation?

### CODE REVIEW

**Comment by cisaacstern** [comment]
@norlandrhagen, at yesterday's Pangeo Forge Coordination Meeting you mentioned that you and @jhamman may have some bandwidth to contribute to this Issue. If that ends up being the case, just wanted to point you to a few resources, to avoid duplication of efforts.

First, I've just added https://github.com/pangeo-forge/flow-charts which provides as a place to collaborate on the graphical portion of this. The charts there are written in GraphViz (which is actually surprisingly great!) but if you don't want to wade into that world, feel free to open PRs against that repo with images (hand drawings, Google Slides, etc.), and I can translate them into GraphViz. (This could be for edits to existing charts, or for requesting new ones be added.)

Second, just a reminder that we previously chatted about some of the programmatic aspects of local recipe testing, here: https://github.com/pangeo-forge/staged-recipes/pull/68#issuecomment-893570820

Finally, the actual changes in the text of this PR may need to be rebased to `master` before further work happens, as I believe the docs have been restructured since the last work happened on this.

Let me know if there's anything else I can help out with.

**Comment by norlandrhagen** [comment]
Hey there @cisaacstern, I have a draft for some additions to `docs/contributions.md`. Do you want me to wait until this branch has been rebased with `master` before opening a PR, or what is the best way to add the edits?

**Comment by cisaacstern** [comment]
Awesome, @norlandrhagen!

I just merged this branch (`redo-contributing`) with `master`. In doing so, I moved the content of what was previously `docs/contribute.md` into `docs/intro_tutorial.md`.

You can now add proposed changed to `docs/intro_tutorial.md` in your fork and open a PR against `pangeo-forge:redo-contributing`. Please let me know if I can provide any further assistance or clarification.

**Comment by cisaacstern** [comment]
@norlandrhagen, sorry... 🤦 something strange seems to have happened with the merge... I'll correct it and get back to you shortly.

**Comment by cisaacstern** [comment]
@norlandrhagen, this is now good to go as described in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/71#issuecomment-921926715. The brief blip (about which you'll likely have received a notification from me) was that I needed to, as you'd correctly pointed out to begin with 😄 , _rebase_ this branch, not merge it.

Looking forward to your contributions.

**Comment by norlandrhagen** [comment]
Awesome thanks! I'll add what I have so far. There are definitely a lot of sections where I could use some input/feedback.

**Comment by rabernat** [comment]
It looks like we can now close this, since it will be superseded by #206?

**Comment by cisaacstern** [comment]
> It looks like we can now close this, since it will be superseded by #206?

Actually no, because #206 is a PR to this PR.

**Comment by rabernat** [comment]
Merging so we can get something up on this page. We can iterate further via future PRs.

**Pull request merged**
