### PR TITLE
Pangeo Forge Cloud user guide

### PR DESCRIPTION
**Pull request by cisaacstern**
WIP for Pangeo Forge Cloud documentation.

Closes https://github.com/pangeo-forge/pangeo-forge-recipes/issues/190 when complete.

### CODE REVIEW

**Comment by cisaacstern** [comment]
@rwegener2, I started this with the aim of just doing a minimal addition to the Cloud docs, but I've ended up with a semi-significant restructure of the docs organization.

The story we're telling just didn't make sense to me without making a clear distinction in the Table of Contents between Pangeo Forge Recipes and Pangeo Forge Cloud.

This is still a WIP, but from a structural perspective what do you think of https://pangeo-forge--328.org.readthedocs.build/en/328/?

**Comment by rwegener2** [comment]
@cisaacstern I really like the clear distinction in the docs. I think it mirrors the line we are trying to draw more broadly so it's a good addition.

As a side note, [this table here](https://pangeo-forge--328.org.readthedocs.build/en/328/pangeo_forge_cloud/pr_checks_reference.html#pr-checks-reference) is pretty cool!  I haven't read the page in detail but the buttons-in-a-table format looks ✨

**Comment by cisaacstern** [comment]
> the buttons-in-a-table format looks ✨

https://github.com/executablebooks/sphinx-panels ftw

**Comment by cisaacstern** [comment]
In the version of this PR (in my mind) which I finished a lot faster and changed a lot less about the docs, I might've been inclined to just merge myself to move fast.

But since this ended up being a pretty large effort, it seems worth pausing for a moment for any potential feedback.

@rwegener2, any notes (even small ones) on https://pangeo-forge--328.org.readthedocs.build/en/328/?

The content of everything except for the Pangeo Forge Cloud header is largely unchanged; almost everything within Pangeo Forge Cloud is new.

I will plan to merge early next week, maybe Tuesday, once I see if @rabernat has any comments.

**Comment by cisaacstern** [comment]
Noting that other projects (Xarray, Dask; see table below) use all caps headers in the menu bar to create 3-tiered organization, whereas this PR proposes we use a clickable dropdown at each tier.

I do think this makes sense for us, because we are solving a different problem than Xarray and Dask are: that is, we're trying to serve documentation for two different things from a single table of contents. Prefect solves this by actually having _two_ separate pages (each with their own table of contents):

Screen Shot 2022-03-18 at 9 24 02 AM


I actually like that we have this all in one table of contents (which makes it easier to cross reference the two docs). But noting that the tradeoff here is that we end up with 3 tiers of dropdown organization:

| Xarray | Dask | Pangeo Forge |
| ------ | ------ | ------ |
| Screen Shot 2022-03-18 at 9 16 40 AM | Screen Shot 2022-03-18 at 9 20 12 AM | Screen Shot 2022-03-18 at 9 18 01 AM |

**Comment by cisaacstern** [comment]
With dropdown organization I like that when I am reading about PF Cloud, for example, I can have the entire PF Recipes navigation collapsed, to really allow me to focus in on the aspect I'm reading about. (This would not be possible with static headers, as in the Dask/Xarray examples above.)


Screen Shot 2022-03-18 at 10 05 27 AM

**Review by rwegener2 — APPROVED** [review]
I think this looks good! I left two small wording suggestions but I like the structure. You're a master of cross referencing and the PR checks reference is really nice. I love the panel display of what the pangeo forge bot says (partially because I love anything with the pangeo forge bot).

I noticed that the Recipe Contribution page references the intro tutorial quite a bit. I'm glad we are pointing people in that direction. I also think that those descriptions are fairly brief and focused on just the OISST dataset. At some point it would be nice to have a reference page dedicated to `meta.yml`. The additional information beyond what is available in the in-line comments of the template would include 1) a list of all possible fields, noting which ones are required and which ones aren't (Ex. maintainer section) 2) a more in depth description of how recipe:recipe works and the case where someone might be maintaining multiple recipes in a single feedstock. This may not be necessary right now, but I'm leaving the note at least as a future reference.

One piece of information that I don't see - how does someone check in on their run or know if it errors? Even if we still don't know the answer to that it might be nice to have a sentence perhaps in the feedstock section like "Once a maintainer triggers your recipe the pangeo forge bot will update the PR with the status of the recipe run".

Overall I'm excited about the expanding docs!

**Comment by cisaacstern** [comment]
Thanks for the thoughtful review, Rachel. Your suggestion for more extensive `meta.yaml` docs is well taken. (Btw, for consistency I've been operating on the assumption that we will only use `.yaml` and not `.yml` as the extension for this file.)

In https://github.com/pangeo-forge/pangeo-forge-recipes/pull/328/commits/0ca6902b7943f8f429da6de4e3f4204fd923f234 I changed "approved recipes" to "production recipes", which I think is both a bit more descriptive of what they are, and hopefully encourages the (accurate) impression of community collaboration vs. a gatekeeping/application process.

Good catch that where to find run logs was definitely under the radar in the PR Reference. I added a more explicit note about that in the last commit which should hopefully make it clearer.

**Pull request merged**
