### PR TITLE
Port tutorial notebooks to use Beam

### LINKED ISSUE #483: Port "Pangeo Forge Recipes" documentation section to use `beam-refactor` approach
The current documentation (#445) describes the Beam approach in the [Introduction Tutorial section](https://pangeo-forge--445.org.readthedocs.build/en/445/introduction_tutorial/index.html). The [Pangeo Forge Recipes section](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/index.html) will also need to be ported to replace e.g. `XarrayZarrRecipe` references with the recommended Beam equivalent.

I guess the final API is still a work in progress (e.g. see #473). If it's useful, I can add a new/update an existing [Recipe Tutorial](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/tutorials/index.html) as this may help settle the approach recommended to recipe authors. We could the update the [Recipes User Guide](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/recipe_user_guide/index.html), [API Reference](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/api_reference.html) etc afterwards.

I have a local CCMP recipe that includes some custom processing (#453), which I can use to create a new recipe tutorial.

**The objective is to have an accurate (if reduced) version of the documentation by Feb 26th 2023.** The following sections will be ported:

- [x] [Recipes User Guide](https://pangeo-forge--499.org.readthedocs.build/en/499/pangeo_forge_recipes/recipe_user_guide/index.html) (#499)
- [Recipe Tutorials](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/tutorials/index.html):
  - [x] [*Xarray-to-Zarr Sequential Recipe: NOAA OISST* notebook](https://pangeo-forge--487.org.readthedocs.build/en/487/pangeo_forge_recipes/tutorials/xarray_zarr/netcdf_zarr_sequential.html) (#487)
  - [x] [*NetCDF Zarr Sequential Recipe: CMIP6*](https://pangeo-forge--487.org.readthedocs.build/en/487/pangeo_forge_recipes/tutorials/xarray_zarr/cmip6-recipe.html) (#487)
  - [x] [*NetCDF Zarr Multi-Variable Sequential Recipe: NOAA World Ocean Atlas* notebook](https://pangeo-forge--487.org.readthedocs.build/en/487/pangeo_forge_recipes/tutorials/xarray_zarr/multi_variable_recipe.html) (#487)
  - [x] [*Complex NetCDF to Zarr Recipe: TerraClimate* ](https://pangeo-forge--490.org.readthedocs.build/en/490/pangeo_forge_recipes/tutorials/xarray_zarr/terraclimate.html) (#490)
  - [x] [*NARR: Subsetting and OPeNDAP*](https://pangeo-forge--500.org.readthedocs.build/en/500/pangeo_forge_recipes/tutorials/xarray_zarr/opendap_subset_recipe.html) (#500)
  - [x] [*HDF Reference Recipe for CMIP6*](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/tutorials/hdf_reference/reference_cmip6.html) (https://github.com/pangeo-forge/pangeo-forge-recipes/pull/486)

- [ ] [API Reference](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/api_reference.html): check docstrings are accurate
- [x] [Development](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/development/index.html)
  * No Beam-related changes required.

### PR DESCRIPTION
**Pull request by derekocallaghan**
This PR will be used to port tutorial notebooks to `beam-refactor`:

The first is an initial port of the *NetCDF Zarr Multi-Variable Sequential Recipe: NOAA World Ocean Atlas* notebook to use the `beam-refactor` approach:
* A custom transform is provided, containing the preprocessor function logic in the non-Beam notebook version. I've included some links to Beam documentation here but this could be expanded if required.
* The recipe approach is similar to that described in [`intro_tutorial_part2`](https://pangeo-forge--445.org.readthedocs.build/en/445/introduction_tutorial/intro_tutorial_part2.html#create-the-recipe-object-beam-composite-transform)
  * It currently creates and specifies a `target_path` to `StoreToZarr`. See #485 for discussion on this point as it may be subject to change.
* I've run it locally and rebuilt the docs, it seems to work without problems. The only issue I spotted was the final plot range is different to the non-Beam version, but I couldn't see what the problem was and I don't think it's related to Beam usage.
* Although it contains references to the [*Xarray-to-Zarr Sequential Recipe: NOAA OISST* notebook](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/tutorials/xarray_zarr/netcdf_zarr_sequential.html), I haven't ported this yet as it contains functionality which may no longer be provided by the `beam-refactor` branch. I'm going to look at this next. In the meantime, this current notebook may be useful as an example for porting other tutorial notebooks (@norlandrhagen).

Partly fixes #483

### CODE REVIEW

**Comment by derekocallaghan** [comment]
I'm going to use this PR for any tutorial notebooks that I port rather than a single PR per notebook. It probably makes more sense to review them together.

**Comment by derekocallaghan** [comment]
Hi @cisaacstern, this PR is ready for review now, involving porting three of the original notebooks, with [one excluded](https://github.com/pangeo-forge/pangeo-forge-recipes/pull/487/commits/046b450e843977bc238c318de406c5973565b1e2). I removed references to `XarrayZarrRecipe` etc in the tutorial index page. The ported notebooks are available at https://pangeo-forge--487.org.readthedocs.build/en/487/pangeo_forge_recipes/tutorials/index.html

The [*HDF Reference Recipe for CMIP6* notebook](https://pangeo-forge--445.org.readthedocs.build/en/445/pangeo_forge_recipes/tutorials/hdf_reference/reference_cmip6.html) hasn't been ported yet as I assume it's dependent on #486. @norlandrhagen is this okay with you?

I'll create separate PRs for the remaining tasklist in #483.

**Comment by derekocallaghan** [comment]
Hi @cisaacstern, if the notebook changes are okay with you, it might be easier to merge this before merging latest `store_name` PR from @yuvipanda (#495). I can update the notebooks afterwards to include the required `store_name` in each `StoreToZarr` usage.

**Comment by derekocallaghan** [comment]
Hi @rabernat and @cisaacstern, if you're free, can you take a look at these notebook changes? If you're happy with them, I'll work on the remaining documentation tasks in #483. Thanks.

**Review by cisaacstern — APPROVED** [review]
@derekocallaghan these look great to me! The illustrations of how to add preprocessors are very clear, and helped me understand how easy that is do with `beam-refactor`. Thanks so much, good to merge IMO!

**Comment by rabernat** [comment]
Psyched to see this PR land! Thanks @derekocallaghan!

**Pull request merged**
