### PR TITLE
Port of Terraclimate example to beam-refactor

### PR DESCRIPTION
**Pull request by norlandrhagen**
https://github.com/pangeo-forge/pangeo-forge-recipes/issues/483

### CODE REVIEW

**Comment by derekocallaghan** [comment]
Hi @norlandrhagen, this looks good and is a lot easier to read now without the previous Prefect output. 

So far, the only thing I've noticed is that `soil_clim` and the corresponding plot aren't visible at: https://pangeo-forge--490.org.readthedocs.build/en/490/pangeo_forge_recipes/tutorials/xarray_zarr/terraclimate.html#check-and-plot-target

Here's the previous non-Beam version with expected output: https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/tutorials/xarray_zarr/terraclimate.html#check-and-plot-target

**Comment by norlandrhagen** [comment]
Thanks for the review @derekocallaghan! I'll fix it today.

**Comment by norlandrhagen** [comment]
Hey there @derekocallaghan, 

When running this recipe I'm getting a killed kernel after about 16 minutes. Did you run into any similar memory issues with the other recipes?

`The Kernel crashed while executing code in the the current cell or a previous cell`

**Comment by derekocallaghan** [comment]
> Hey there @derekocallaghan,
> 
> When running this recipe I'm getting a killed kernel after about 16 minutes. Did you run into any similar memory issues with the other recipes?
> 
> `The Kernel crashed while executing code in the the current cell or a previous cell`

Hi @norlandrhagen, I didn't have any similar kernel issues with the other recipes. At first I thought it might be related to the number of products being processed (I had to ensure pruning with some of the others) but looking at the new vs old notebooks above, it looks like you're using the same chunk spec as the old.

Does it happen when running/debugging the pipeline outside of Jupyter?

**Comment by cisaacstern** [comment]
@norlandrhagen, #521 is nearly done, so I've merged that work here, in hopes of being able to run the terraclimate tutorial (which was previously blocked by #517).

In my first attempt to run this notebook, I am still seeing a killed kernel on the cell which attempts to run the pipeline.

I'll take a closer look again at this tomorrow morning.

**Comment by cisaacstern** [comment]
This is the last major item before merging `beam-refactor`.

@norlandrhagen, I'm working on this right now! Should have something soon.

**Comment by cisaacstern** [comment]
Ok! IMHO this is good to go. I narrowed it down to two variables to make it more manageable to run. To get `beam-refactor` merged today, I'm going to merge this now. Happy to look at follow-on issues/PRs if anyone notices anything I overlooked.

**Pull request merged**
