### PR TITLE
Use uvloop event loop

### PR DESCRIPTION
**Pull request by davidbrochart**
It seems to solve the issue with the hanging HTTP tests, or maybe it makes them much more unlikely...

### CODE REVIEW

**Comment by martindurant** [comment]
Is uvloop being used by fsspec, the server, or both?
It ought to be perfectly compatible with fsspec, but I'm not aware of it being used elsewhere. fsspec does do some low-level event loop things in certain conditions (nested calls).

**Comment by davidbrochart** [comment]
> Is uvloop being used by fsspec, the server, or both?

Only by fsspec.

> It ought to be perfectly compatible with fsspec, but I'm not aware of it being used elsewhere. fsspec does do some low-level event loop things in certain conditions (nested calls).

As long as fsspec doesn't patch asyncio's code, uvloop should be a drop-in replacement.
FYI, the issue seems to boil down to `asyncio.run_coroutine_threadsafe(f(), loop=loop)` not actually calling `f` [here](https://github.com/intake/filesystem_spec/blob/4d03e1e07ada08f91784e7826c355da71a13aa1e/fsspec/asyn.py#L62).

**Comment by martindurant** [comment]
Can you explain further? Why would f not run or get stuck?

On February 17, 2021 6:16:03 PM EST, David Brochart <notifications@github.com> wrote:
>> Is uvloop being used by fsspec, the server, or both?
>
>Only by fsspec.
>
>> It ought to be perfectly compatible with fsspec, but I'm not aware of
>it being used elsewhere. fsspec does do some low-level event loop
>things in certain conditions (nested calls).
>
>As long as fsspec doesn't patch asyncio's code, uvloop should be a
>drop-in replacement.
>FYI, the issue seems to boil down to
>`asyncio.run_coroutine_threadsafe(f(), loop=loop)` not actually calling
>`f`
>[here](https://github.com/intake/filesystem_spec/blob/4d03e1e07ada08f91784e7826c355da71a13aa1e/fsspec/asyn.py#L62).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pangeo-forge/pangeo-forge/pull/76#issuecomment-780916916

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davidbrochart** [comment]
I have no explanation, I stopped investigating after checking that when it hangs, it is because `asyncio.run_coroutine_threadsafe(f(), loop=loop)` doesn't run `f`. Next step is looking at asyncio's code, but this is becoming very strange.

**Comment by davidbrochart** [comment]
BTW, I was wondering why there is this kind of polling [here](https://github.com/intake/filesystem_spec/blob/4d03e1e07ada08f91784e7826c355da71a13aa1e/fsspec/asyn.py#L67-L68). I think you could just `e.wait()`.

**Comment by martindurant** [comment]
That was copied from `distributed` - happy to change it. Note, that I don't think any of the code calls with a timeout, so the whole function could be a bit simpler. On the other hand, perhaps exactly a timeout would have prevented the hanging.

**Comment by davidbrochart** [comment]
There are things that look suspicious in the code, although I've not been able to prove they're responsible for the hanging. For instance, don't you have to use a lock when you set/get variables from different threads, [here](https://github.com/intake/filesystem_spec/blob/4d03e1e07ada08f91784e7826c355da71a13aa1e/fsspec/asyn.py#L51), [here](https://github.com/intake/filesystem_spec/blob/4d03e1e07ada08f91784e7826c355da71a13aa1e/fsspec/asyn.py#L59) and [there](https://github.com/intake/filesystem_spec/blob/4d03e1e07ada08f91784e7826c355da71a13aa1e/fsspec/asyn.py#L88-L90)?

**Comment by martindurant** [comment]
`thread_state` is a thread-local variable, so those are fine.

**Comment by rabernat** [comment]
I've been neglecting this, sorry. I don't really understand this stuff, so if you two agree this approach is the right one, I'm happy to merge. Are we at a consensus?

**Comment by davidbrochart** [comment]
I don't understand either what is the cause of the issue, I just saw that using uvloop seems to solve it. Not sure we should merge this PR.

**Comment by martindurant** [comment]
Do you want to try with https://github.com/intake/filesystem_spec/pull/572 ?

**Comment by rabernat** [comment]
@martindurant - do you mean run the test suite unchanged with an unreleased version of fsspec? Yes, I'd be happy to try it. Could you make a new PR to update the test env?

**Comment by martindurant** [comment]
Not even merged at the moment, so would have to install from the branch, i.e., good to see if the CI works, but you wouldn't want to merge the PR.

**Pull request closed without merging**
