### PR TITLE
Restore File Pattern Docs (with Globus workaround)

### LINKED ISSUE #558: Is the Globus workaround from #408 still supported with v0.10.x?
I am discussing moving data from GFDL into LEAP/m2lines cloud buckets (with @adcroft), and just scrolled through some past issues/PRs on the matter (#222, #408). In particular I am wondering if the approach in #408 is still valid with the beam refactor. 
The parts of the docs seem to have been removed, but I am not sure why something in the `file_pattern` API would have necessarily changed, even though I might be missing something here. 

If this is generally still applicable Id be happy to try this out.

### PR DESCRIPTION
**Pull request by jbusecke**
Closes #558. 

This so far is a simple copy and past based on @rabernat s [comment](https://github.com/pangeo-forge/pangeo-forge-recipes/issues/558#issuecomment-1670010751). Could someone confirm that all the information added is in fact working for the new beam version?

### CODE REVIEW

**Comment by rabernat** [comment]
> Could someone confirm that all the information added is in fact working for the new beam version?

Unfortunately I think the best candidate to confirm this would be you. 😬

**Comment by cisaacstern** [comment]
> Unfortunately I think the best candidate to confirm this would be you. 

@jbusecke, I would have to agree 😆 . Thanks for all your hard work of late!

**Comment by jbusecke** [comment]
Looool. I would say LGTM and Ill promise to raise/correct issues once I test things (particularly with globus).

**Comment by cisaacstern** [comment]
Sounds like a plan.

**Pull request merged**
