### PR TITLE
Remove prefect and dask executors

### PR DESCRIPTION
**Pull request by norlandrhagen**
https://github.com/pangeo-forge/pangeo-forge-recipes/issues/475

### CODE REVIEW

**Comment by cisaacstern** [comment]
Nice, @norlandrhagen! Thanks for all the work on multiple fronts!

**Comment by yuvipanda** [comment]
I fixed the failing test in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/491

**Comment by yuvipanda** [comment]
And I fix the pre-commit test in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/492

**Comment by norlandrhagen** [comment]
Thanks @yuvipanda!

**Pull request merged**
