### PR TITLE
Feature/add tiff file opt

### PR DESCRIPTION
**Pull request by norlandrhagen**

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks for working on this Raphael! Let us know how we can help.

**Comment by norlandrhagen** [comment]
Thanks @rabernat! Yeah, this tiny update worked on a recipe of tiff files. Any other tests to add or additions to the docs you would suggest?

**Comment by cisaacstern** [comment]
@norlandrhagen, thanks for working on this! In order for this `FileType` to translate to the selection of the correct xarray backend at runtime, you'll also need to add an entry to

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/d1875c3f483188ed72e34177c58bc896b947aa76/pangeo_forge_recipes/recipes/xarray_zarr.py#L39-L42

probably 

```python
FileType.tiff: dict(engine="rasterio")
```

?

In terms of testing, all members of `FileType` are automatically tested for, basically, existence here:

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/d1875c3f483188ed72e34177c58bc896b947aa76/tests/test_patterns.py#L188-L189

A more ambitious testing path would be to generate some synthetic GeoTIFF data, as we do in the test suite for NetCDF data, and then try running an XarrayZarrRecipe with it. IMO that's rather ambitious and perhaps beyond the scope of what's necessary for this PR.

**Comment by norlandrhagen** [comment]
Thanks for the feedback! I incorporated your edits in the `OPENER_MAP`

**Comment by cisaacstern** [comment]
I think the test failures are because Prefect 2.0 was released since the last time we ran these tests.

To get them to pass, we'll need to pin Prefect to the last pre-2.0 release in the ci environments:

https://github.com/pangeo-forge/pangeo-forge-recipes/tree/master/ci

**Comment by norlandrhagen** [comment]
Sounds good. I can open up a separate PR for that. It looks like they slightly changed the way the `DaskExecutor` is imported, so might have to make a few code tweaks.

**Comment by cisaacstern** [comment]
We will soon be dropping Prefect entirely, so I would suggest going back to the latest version of Prefect which does not require any tweaks to `pangeo-forge-recipes` code, however old that is. Thanks Raphael!

**Comment by norlandrhagen** [comment]
Ah icic, I misread your comment!

**Comment by cisaacstern** [comment]
With #398 merged, merging from upstream should resolve test failures here.

**Comment by cisaacstern** [comment]
@norlandrhagen, do you have pre-commit installed locally, and if so is your local pre-commit passing?

> If you don't have it installed locally, from your repo root, you should be able to just `pip install pre-commit` and then call `pre-commit install` followed by `pre-commit run --all-files`.

I'm not sure what this pre-commit error we're seeing is, and just wondering if it's GitHub Actions-specific, or not.

**Comment by norlandrhagen** [comment]
Hmm, pre-commit seems to be passing?

image

**Comment by cisaacstern** [comment]
Hmm yeah that's odd. I'll pull this branch and see if I can fix this.

**Comment by norlandrhagen** [comment]
Thanks!

**Comment by cisaacstern** [comment]
@norlandrhagen, I think what happened is that, when pre-commit runs automatically at commit time, it only checks files that were changed in that commit (this might be configurable). I made the fix by manually calling `pre-commit run --all-files`, which ensures that all files are re-formatted, and this seems to have resolved the issue.

If we could just do one last check on this PR, I think we'll be glad we did. Specifically, this PR aims to close https://github.com/pangeo-forge/pangeo-forge-recipes/issues/392, in which you mentioned getting some errors when trying to run a recipe with TIFF inputs. Could I ask that you just manually verify that installing `pangeo-forge-recipes` from

```
pip install "git+http://github.com/norlandrhagen/pangeo-forge-recipes.git@feature/add_tiff_file_opt"
```

resolves the issue you reported in the #392? Writing true tests for this I think is beyond the scope of what we'll want to get into now, but if you could just manually check that this branch solves your issue, it could give us a bit more confidence that we won't have to circle back with another PR to fix #392.

**Comment by norlandrhagen** [comment]
@cisaacstern just installed this branch and tested a simple recipe that opened tiffs. I think this PR is ready to merge if that works for you.

**Comment by cisaacstern** [comment]
Awesome, sounds good to me. Thanks for this contribution, @norlandrhagen! And for your patience with the issues that came up along the way, such as #398. I'll merge now.

**Comment by norlandrhagen** [comment]
Glad to to help out a bit!

**Pull request merged**
