### PR TITLE
Add netcdf3 support for kerchunk

### PR DESCRIPTION
**Pull request by rabernat**
This attempts to add the ability to use kerchunk on netcdf3 files. This would maybe be a fix to move forward https://github.com/pangeo-forge/staged-recipes/pull/140.

However, when trying this out, I immediately hit https://github.com/fsspec/kerchunk/issues/187

Example recipe

```python
from pangeo_forge_recipes.patterns import ConcatDim, FilePattern, FileType
from pangeo_forge_recipes.recipes import XarrayZarrRecipe
from pangeo_forge_recipes.storage import StorageConfig, FSSpecTarget, CacheFSSpecTarget, MetadataTarget

def make_snapshot_url(time):
    url_format = (
        'https://g-f83d26.7a577b.6fbd.data.globus.org/'
        f'nw2_0.25deg_N15_baseline_hmix5/snapshots_{time:08d}.nc'
    )
    return url_format.format(time=time)

time_concat_dim = ConcatDim(
    "time",
    [30005], # 30505, 31005, 31505],
    nitems_per_file=100
)
        
pattern = FilePattern(make_snapshot_url, time_concat_dim, file_type=FileType.netcdf3)

recipe = XarrayZarrRecipe(
    pattern,
    subset_inputs={'time': 20},
    xarray_open_kwargs = {"decode_times": False},
    open_input_with_kerchunk=True
)
```

### CODE REVIEW

**Comment by martindurant** [comment]
I am working on this now, as well as a more consistent API. I will start with the simplest options for NetCDF3 first and use your snapshot url as the test case.

**Comment by rabernat** [comment]
We would be happy to join a call to discuss API design and software architecture questions.

**Comment by rabernat** [comment]
Tests are failing due to dependence on unreleased kerchunk features. @martindurant - could you make a release soon?

**Comment by martindurant** [comment]
Done: 0.0.7

**Comment by rabernat** [comment]
The recipe in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/383#issue-1302632785 now works with this PR + latest Kerchunk.

**Comment by cisaacstern** [comment]
@rabernat, following on https://github.com/pangeo-forge/pangeo-forge-recipes/issues/361#issuecomment-1260096498, with the release of kerchunk 0.0.7, is the only think left to do here pinning `kerchunk>=0.0.7`?

**Comment by andersy005** [comment]
> @rabernat, following on [#361 (comment)](https://github.com/pangeo-forge/pangeo-forge-recipes/issues/361#issuecomment-1260096498), is the only thing left to do here pinning `kerchunk>=0.0.7`?


@rabernat the gentlest of bumps on this :)

**Comment by cisaacstern** [comment]
Awesome! I will make a new release and push this up to Pangeo Forge Cloud.

**Comment by rabernat** [comment]
Let's try to get #462 in today before releasing.

**Pull request merged**
