### PR TITLE
Restructure docs

### PR DESCRIPTION
**Pull request by rabernat**
This restructures the docs in line with https://github.com/pangeo-forge/pangeo-forge-vue-website/pull/8 and https://github.com/pangeo-forge/roadmap/issues/25.

It's not complete...some things need to be filled in. But it gives us a place to put the new content.

cc @cisaacstern @rwegener2

### CODE REVIEW

**Comment by rwegener2** [comment]
Thanks for getting this rolling @rabernat.  I was hoping to view the changes by building and running the sphinx docs locally.  Would you be able to briefly share how you do that?  The [sphinx docs](https://www.sphinx-doc.org/en/master/usage/quickstart.html) explain some build and run commands, but I'm wondering about environment.  I don't see an environment file but I do see the Dockerfile.  Is there a `docker-compose` command you' typically use?  Thank you!

**Comment by rabernat** [comment]
> I was hoping to view the changes

One option is to use the RTD preview build:

image

https://pangeo-forge--178.org.readthedocs.build/en/178/

> ...by building and running the sphinx docs locally.

This is a bit more involved. We need to create some developer documentation which explains how to do this. The basic steps are

- Clone this repo
- Create a new, empty virtual environment, e.g. `conda create -n pangeo-forge-docs python=3.9`
- Install the doc requirements, e.g. `pip install -r ./docs/requirements.txt`
- Build the docs: `doc docs; make html`
- Preview the docs: `cd _build/html; python -m http.server`

**Review by cisaacstern — CHANGES_REQUESTED** [review]
This is awesome, Ryan.

My only suggestion is that we point the [repo link](https://github.com/rabernat/pangeo-forge/blob/restructure-docs/docs/conf.py#L35) to the Pangeo Forge org, rather than the recipes repo. And accordingly, maybe we should remove the [`extlinks`](https://github.com/rabernat/pangeo-forge/blob/d54e2075f71aebc8d1906fa3d96e135660a8b2b4/docs/conf.py#L19-L20), and to set [`use_issues_button == False`](https://github.com/rabernat/pangeo-forge/blob/d54e2075f71aebc8d1906fa3d96e135660a8b2b4/docs/conf.py#L39)?

**Comment by rabernat** [comment]
> My only suggestion is that we point the [repo link](https://github.com/rabernat/pangeo-forge/blob/restructure-docs/docs/conf.py#L35) to the Pangeo Forge org, rather than the recipes repo

I see your point, but those changes will break several current features. Despite the more general nature of the documentation, it is useful to have these links point to the actual github repo where the documentation lives, which is still _this_ repo. Let's leave as is for now.

**Pull request merged**
