### PR TITLE
Serialize file patterns

### LINKED ISSUE #116: Improve serializability of Recipe and related classes
After the refactor in #101, our dask graphs have gotten a lot bigger.

I did the following, based on the NOAA OISST recipe from the docs

```python
import pandas as pd
import s3fs
import gcsfs
import json

from pangeo_forge.patterns import pattern_from_file_sequence
from pangeo_forge.recipes import XarrayZarrRecipe
from pangeo_forge.storage import FSSpecTarget, CacheFSSpecTarget

# set up recipe

input_url_pattern = (
    "https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation"
    "/v2.1/access/avhrr/{yyyymm}/oisst-avhrr-v02r01.{yyyymmdd}.nc"
)

dates = pd.date_range("1981-09-01", "2021-01-05", freq="D")
input_urls = [
    input_url_pattern.format(
        yyyymm=day.strftime("%Y%m"), yyyymmdd=day.strftime("%Y%m%d")
    )
    for day in dates
]

pattern = pattern_from_file_sequence(input_urls, "time", nitems_per_file=1)
recipe = XarrayZarrRecipe(pattern, inputs_per_chunk=5)

# set up storage

fmt = 'zarr'
recipe_key = 'oisst_avhrr_v02r01'
recipe_name = f'{feedstock_name}/{recipe_key}'

feedstock_name = 'noaa_oisst'

cache_base = f'gs://pangeo-forge-us-central1/pangeo-forge-cache'
metadata_base = f'gs://pangeo-forge-us-central1/pangeo-forge-metadata'

with open('pangeo-181919-cc01a4fbb1ef.json') as fp:
    token = json.load(fp)
fs_gcs = gcsfs.GCSFileSystem(token=token, cache_timeout=-1, cache_type="none")

endpoint_url = 'https://ncsa.osn.xsede.org'
fs_osn = s3fs.S3FileSystem(
    key=osn_key,
    secret=osn_secret,
    client_kwargs={'endpoint_url': endpoint_url},
    default_cache_type='none',
    default_fill_cache=False,
    listings_expiry_time=0.01,
)

target_base = f's3://Pangeo/pangeo-forge'
recipe.input_cache = CacheFSSpecTarget(fs_gcs, f"{cache_base}/{recipe_name}")
recipe.metadata_cache = FSSpecTarget(fs_gcs, f"{metadata_base}/{recipe_name}")
recipe.target = FSSpecTarget(fs_osn, f"{target_base}/{recipe_name}.{fmt}") 
```

Then I converted it to a dask delayed object to execute on a Dask Gateway cluster

```python
from pangeo_forge.executors import PythonPipelineExecutor
executor_dask = DaskPipelineExecutor()
pl = recipe.to_pipelines()
plan = executor_dask.pipelines_to_plan(pl)  # dask.Delayed obj
```

The graph is about 10 MB, not huge, right?
```python
import cloudpickle
serialized = cloudpickle.dumps(plan.dask)
len(serialized)
# -> 10620079
```

But when I call
```python
dask.persist(plan, retries=5)
```

I quickly run out of memory in my notebook pod (16 GB) before the the `persist` call finished. I also tried with `, optimize_graph=False`.

One culprit could be the new FilePattern class, which stores a big xarray dataset internally
https://github.com/pangeo-forge/pangeo-forge/blob/1c5f3520d6fdca718cb372d60161d4fd8617dcbb/pangeo_forge/patterns.py#L81

I feel like we could optimize this using `__getstate__` / `__setstate`.

@martindurant it would be great if you could look at this.

### PR DESCRIPTION
**Pull request by rabernat**
This PR potentially closes #116 by making the FilePattern object smaller in serialized form.

### CODE REVIEW

**Comment by cisaacstern** [comment]
In reviewing the `copy_pruned()` PR, I realized that I do not really get what pickling is, why its valuable, and when we need to use it: https://github.com/pangeo-forge/pangeo-forge-recipes/pull/139#discussion_r635434855

Re-posting here as an invitation to further discussion.

**Comment by TomAugspurger** [comment]
I think this does help. Using this test for 1000 items we went from ~2s to 1s.

<details>

```python
import pandas as pd
import json
import fsspec
from timeit import default_timer as tic

from pangeo_forge_recipes.patterns import pattern_from_file_sequence
from pangeo_forge_recipes.recipes import XarrayZarrRecipe
from pangeo_forge_recipes.storage import FSSpecTarget, CacheFSSpecTarget

import dask
from distributed import Client
from dask.highlevelgraph import HighLevelGraph

def main():
    feedstock_name = "abc"
    # set up recipe

    input_url_pattern = (
        "https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation"
        "/v2.1/access/avhrr/{yyyymm}/oisst-avhrr-v02r01.{yyyymmdd}.nc"
    )

    dates = pd.date_range("1981-09-01", "2020-01-05", freq="D")
    input_urls = [
        input_url_pattern.format(
            yyyymm=day.strftime("%Y%m"), yyyymmdd=day.strftime("%Y%m%d")
        )
        for day in dates
    ]
    input_urls = input_urls[:1000]

    print(len(input_urls))
    pattern = pattern_from_file_sequence(input_urls, "time", nitems_per_file=1)
    recipe = XarrayZarrRecipe(pattern, inputs_per_chunk=5)

    # set up storage

    fmt = 'zarr'
    recipe_key = 'oisst_avhrr_v02r01'
    recipe_name = f'{feedstock_name}/{recipe_key}'

    feedstock_name = 'noaa_oisst'

    cache_base = f'gs://pangeo-forge-us-central1/pangeo-forge-cache'
    metadata_base = f'gs://pangeo-forge-us-central1/pangeo-forge-metadata'
    endpoint_url = 'https://ncsa.osn.xsede.org'
    fs_gcs = fsspec.get_filesystem_class("memory")("gcs")
    fs_osn = fsspec.get_filesystem_class("memory")("osn")

    target_base = f's3://Pangeo/pangeo-forge'
    recipe.input_cache = CacheFSSpecTarget(fs_gcs, f"{cache_base}/{recipe_name}")
    recipe.metadata_cache = FSSpecTarget(fs_gcs, f"{metadata_base}/{recipe_name}")
    recipe.target = FSSpecTarget(fs_osn, f"{target_base}/{recipe_name}.{fmt}") 

    from pangeo_forge_recipes.executors import DaskPipelineExecutor
    executor_dask = DaskPipelineExecutor()
    pl = recipe.to_pipelines()
    plan = executor_dask.pipelines_to_plan(pl)  # dask.Delayed obj
    dsk2 = HighLevelGraph.from_collections("x", plan.dask)
    keys = list(plan.dask)

    with Client() as client:
        t0 = tic()
        x = dsk2.__dask_distributed_pack__(client, keys)
        t1 = tic()

        print(t1 - t0)

if __name__ == "__main__":
    main()
```

</details>

But for larger ones, there's still work to be done. I'll look at it for a bit.

**Comment by cisaacstern** [comment]
@TomAugspurger, in order to define filesystems with
```python
    fs_gcs = fsspec.get_filesystem_class("memory")("gcs")
    fs_osn = fsspec.get_filesystem_class("memory")("osn")
```
do you first register credentialed `gcsfs` and `s3fs` classes with [`fsspec.registery.register_implementation`](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.registry.register_implementation)?

Since it looks like you run `main()` from the command line, how do you get these `fsspec.registry` additions discoverable in the runtime namespace?

Currently I'm manually writing recipes to OSN from a local notebook (with inline creds), but I would much prefer to run something like what you have above.

**Comment by martindurant** [comment]
This line
```
fsspec.get_filesystem_class("memory")("gcs")
```
is the same as
```
fsspec.filesystem"memory",  "gcs")
```
but the memory filesystem doesn't actually take any arguments. This will ensure that the two instances are not the same, but *warning* they will share the same underlying dict storage (before this is global at the class level).

**Comment by TomAugspurger** [comment]
> Currently I'm manually writing recipes to OSN from a local notebook (with inline creds), but I would much prefer to run something like what you have above.

Just an FYI, my filesystems in that snippet aren't actually capable of writing anywhere (other than local memory). The names `fs_gcs` and `fs_osn` are just leftover's from Ryan's original script.

---

I think the best path forward here is to construct a custom [HighLevelGraph](https://docs.dask.org/en/latest/high-level-graphs.html) (or perhaps a `Layer`, I haven't kept up to date but layer seems like the more appropriate class these days), focusing on the `cache_input` stage. Right now that has stage of the graph grows linearly with the number of inputs. I'll need to check the general case, but at least for the test case the layer is really simple:

```python
from dask.highlevelgraph import Layer

class CacheInputLayer(Layer):
    def __init__(self, annotations=None, func=None, n=None):
        self.token = dask.base.tokenize(func)
        self.func = func
        self.n = n
        super().__init__(annotations=annotations)

    def __getitem__(self, index):
        token, n = index
        if token == self.token and isinstance(n, int) and (0 <= n < self.n):
            return (self.func, n)
        
    def __len__(self):
        return self.n
    
    def __iter__(self):
        for i in range(self.n):
            yield (self.func, i)
        
    def is_materialized(self):
        return False


cache_input = pl[0][0]
layer = CacheInputLayer(func=cache_input.func, n=len(cache_input.map_args))
```

A single instance of that class will replace the `n` inputs 14,006 in the full example. (Note that the class doesn't implement any kind of error checking, etc.). Then it doesn't really matter how large / slow the `FilePattern` is to serialize since we only have one.

I don't know when I'll have time to get to this, so if anyone wants to dig into it feel free. Otherwise I'll try to over the next couple weeks.

**Pull request merged**
