### PR TITLE
Try tests with per-thread loop for http

### PR DESCRIPTION
**Pull request by martindurant**
ref: #76

### CODE REVIEW

**Comment by martindurant** [comment]
Well, everything passes except for something with blosc

**Comment by davidbrochart** [comment]
Let's restart the jobs, failures were kind of random, but that's great news. So there was a bug in fsspec?

**Comment by martindurant** [comment]
> So there was a bug in fsspec?

Not exactly. The event loop was being run in a particular event loop, and all IO channelled through it, while the thread launching the IO work would wait. Event loops are not thread-safe, but this mostly worked so long as there were no other event loops around. I think actually it was a change in aiohttp that made the difference, that they would require to run their requests in an `sync with` block, whereas before `await` would do. In any case, there is now one event loop per thread, which starts and stops as IO stuff is needed.

**Comment by davidbrochart** [comment]
Blosc error again, restarting.

**Comment by davidbrochart** [comment]
> In any case, there is now one event loop per thread, which starts and stops as IO stuff is needed.

I'm evaluating this technique in [jupyter-client](https://github.com/jupyter/jupyter_client), but it's not an ideal solution either. In the end I've found that having the sync API run async funtions until complete is the best, like we did in [nbclient](https://github.com/jupyter/nbclient), but that requires using [nest-asyncio](https://github.com/erdewit/nest_asyncio) which patches the event loop, so not an ideal solution either. I wish reentrant event loops were possible in standard asyncio, but [core devs are not in favor of it](https://bugs.python.org/issue22239).

**Comment by martindurant** [comment]
> using nest-asyncio which patches the event loop

I don't think that would be acceptable to fsspec users, unfortunately, because they may be using those async-related classes for other things

> I wish reentrant event loops were possible in standard asyncio

Me too!

`fsspec.async._run_until_done` is my internal nested async runner; but I intend to rewrite a bit to remove its need.

**Comment by rabernat** [comment]
So is our conclusion that the fsspec fix will fix our problem? If so, great!

**Comment by davidbrochart** [comment]
It looks like it, let's relaunch the tests a few times to make sure.

**Comment by davidbrochart** [comment]
I ran the tests a dozen times and never saw them hanging.

**Comment by rabernat** [comment]
I'm curious why this works but #85 does not.

Could someone rebase this PR on the latest master to see if the issue is with the new tests introduced in #78?

**Comment by rabernat** [comment]
This seems to be resolved in latest master so closing.

**Pull request closed without merging**
